
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AIRLINE AREA AT BOOK BOOKINGS CANCEL CONCERT CONFIRM DATE FOOTBALL FOR FROM IDENTIFIER IN LIST MATCH MY ON PAY STRING TICKETS TIME TO TRAIN VIEWstatement : list_command\n                 | booking_command\n                 | status_command\n                 | view_commandlist_command : LIST event_type TICKETS IN MY AREAbooking_command : book_transport\n                      | book_eventbook_transport : BOOK TRAIN FROM location TO location ON DATE AT TIME FOR person\n                     | BOOK AIRLINE FROM location TO location ON DATE AT TIME FOR personbook_event : BOOK event_name CONCERT FOR person\n                 | BOOK event_name FOOTBALL MATCH FOR personstatus_command : CONFIRM event_type FOR person\n                      | PAY event_type FOR person\n                      | CANCEL event_type FOR personview_command : VIEW BOOKINGSevent_type : CONCERT\n                 | FOOTBALL\n                 | TRAIN\n                 | AIRLINElocation : IDENTIFIER\n               | STRING\n               | location IDENTIFIERperson : IDENTIFIER\n             | STRING\n             | person IDENTIFIERevent_name : IDENTIFIER\n                 | STRING\n                 | event_name IDENTIFIER'
    
_lr_action_items = {'LIST':([0,],[6,]),'CONFIRM':([0,],[9,]),'PAY':([0,],[10,]),'CANCEL':([0,],[11,]),'VIEW':([0,],[12,]),'BOOK':([0,],[13,]),'$end':([1,2,3,4,5,7,8,22,38,39,40,41,42,50,54,56,59,70,71,],[0,-1,-2,-3,-4,-6,-7,-15,-12,-23,-24,-13,-14,-25,-10,-5,-11,-8,-9,]),'CONCERT':([6,9,10,11,25,26,27,36,],[15,15,15,15,34,-26,-27,-28,]),'FOOTBALL':([6,9,10,11,25,26,27,36,],[16,16,16,16,35,-26,-27,-28,]),'TRAIN':([6,9,10,11,13,],[17,17,17,17,23,]),'AIRLINE':([6,9,10,11,13,],[18,18,18,18,24,]),'BOOKINGS':([12,],[22,]),'IDENTIFIER':([13,25,26,27,29,30,31,32,33,36,38,39,40,41,42,43,44,45,46,47,50,51,52,53,54,55,57,58,59,68,69,70,71,],[26,36,-26,-27,39,39,39,44,44,-28,50,-23,-24,50,50,52,-20,-21,52,39,-25,44,-22,44,50,39,52,52,50,39,39,50,50,]),'STRING':([13,29,30,31,32,33,47,51,53,55,68,69,],[27,40,40,40,45,45,40,45,45,40,40,40,]),'TICKETS':([14,15,16,17,18,],[28,-16,-17,-18,-19,]),'FOR':([15,16,17,18,19,20,21,34,48,66,67,],[-16,-17,-18,-19,29,30,31,47,55,68,69,]),'FROM':([23,24,],[32,33,]),'IN':([28,],[37,]),'MATCH':([35,],[48,]),'MY':([37,],[49,]),'TO':([43,44,45,46,52,],[51,-20,-21,53,-22,]),'ON':([44,45,52,57,58,],[-20,-21,-22,60,61,]),'AREA':([49,],[56,]),'DATE':([60,61,],[62,63,]),'AT':([62,63,],[64,65,]),'TIME':([64,65,],[66,67,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'list_command':([0,],[2,]),'booking_command':([0,],[3,]),'status_command':([0,],[4,]),'view_command':([0,],[5,]),'book_transport':([0,],[7,]),'book_event':([0,],[8,]),'event_type':([6,9,10,11,],[14,19,20,21,]),'event_name':([13,],[25,]),'person':([29,30,31,47,55,68,69,],[38,41,42,54,59,70,71,]),'location':([32,33,51,53,],[43,46,57,58,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> list_command','statement',1,'p_statement','lexer_parser.py',292),
  ('statement -> booking_command','statement',1,'p_statement','lexer_parser.py',293),
  ('statement -> status_command','statement',1,'p_statement','lexer_parser.py',294),
  ('statement -> view_command','statement',1,'p_statement','lexer_parser.py',295),
  ('list_command -> LIST event_type TICKETS IN MY AREA','list_command',6,'p_list_command','lexer_parser.py',299),
  ('booking_command -> book_transport','booking_command',1,'p_booking_command','lexer_parser.py',303),
  ('booking_command -> book_event','booking_command',1,'p_booking_command','lexer_parser.py',304),
  ('book_transport -> BOOK TRAIN FROM location TO location ON DATE AT TIME FOR person','book_transport',12,'p_book_transport','lexer_parser.py',308),
  ('book_transport -> BOOK AIRLINE FROM location TO location ON DATE AT TIME FOR person','book_transport',12,'p_book_transport','lexer_parser.py',309),
  ('book_event -> BOOK event_name CONCERT FOR person','book_event',5,'p_book_event','lexer_parser.py',320),
  ('book_event -> BOOK event_name FOOTBALL MATCH FOR person','book_event',6,'p_book_event','lexer_parser.py',321),
  ('status_command -> CONFIRM event_type FOR person','status_command',4,'p_status_command','lexer_parser.py',329),
  ('status_command -> PAY event_type FOR person','status_command',4,'p_status_command','lexer_parser.py',330),
  ('status_command -> CANCEL event_type FOR person','status_command',4,'p_status_command','lexer_parser.py',331),
  ('view_command -> VIEW BOOKINGS','view_command',2,'p_view_command','lexer_parser.py',338),
  ('event_type -> CONCERT','event_type',1,'p_event_type','lexer_parser.py',342),
  ('event_type -> FOOTBALL','event_type',1,'p_event_type','lexer_parser.py',343),
  ('event_type -> TRAIN','event_type',1,'p_event_type','lexer_parser.py',344),
  ('event_type -> AIRLINE','event_type',1,'p_event_type','lexer_parser.py',345),
  ('location -> IDENTIFIER','location',1,'p_location','lexer_parser.py',349),
  ('location -> STRING','location',1,'p_location','lexer_parser.py',350),
  ('location -> location IDENTIFIER','location',2,'p_location','lexer_parser.py',351),
  ('person -> IDENTIFIER','person',1,'p_person','lexer_parser.py',358),
  ('person -> STRING','person',1,'p_person','lexer_parser.py',359),
  ('person -> person IDENTIFIER','person',2,'p_person','lexer_parser.py',360),
  ('event_name -> IDENTIFIER','event_name',1,'p_event_name','lexer_parser.py',367),
  ('event_name -> STRING','event_name',1,'p_event_name','lexer_parser.py',368),
  ('event_name -> event_name IDENTIFIER','event_name',2,'p_event_name','lexer_parser.py',369),
]
